name = "sha1"
description = "Secure Hash Algorithm 1 implemented in Ada"
version = "2.0.0"
website = "https://github.com/AntonMeep/sha1"
licenses = "ISC"
tags = ["cryptography", "security", "sha1"]

authors = ["Anton Fediushin"]
maintainers = ["Anton Fediushin <imantonmeep@gmail.com>"]
maintainers-logins = ["AntonMeep"]
